TILE_SIZE = 28
GRID_W = 36
GRID_H = 24
SCREEN_W = GRID_W * TILE_SIZE
SCREEN_H = GRID_H * TILE_SIZE
FPS = 60

BUILDING_CHANCE = 0.38
TREE_CHANCE = 0.30

TEXT_COLOR = (24, 24, 24)
FONT_NAME = "consolas"
FONT_SIZE = 18

GAME_TITLE = "Matthew's Mini Town - A to B"
