TILE_SIZE = 28
GRID_W = 36
GRID_H = 24
HUD_HEIGHT = 140
SCREEN_W = GRID_W * TILE_SIZE
SCREEN_H = HUD_HEIGHT + (GRID_H * TILE_SIZE)
FPS = 60

BUILDING_CHANCE = 0.38
TREE_CHANCE = 0.30

TEXT_COLOR = (24, 24, 24)
FONT_NAME = "consolas"
FONT_SIZE = 18

GAME_TITLE = "Matthew's Mini Town - A to B"

COLLECTIBLE_POINTS = 10
COMBO_WINDOW_SECONDS = 10
COMBO_MULTIPLIER_CAP = 5
FINISH_TIME_TARGET_SECONDS = 120
FINISH_BONUS_POINTS = 100
HIGH_SCORE_FILE = "high_score.json"

NPC_MOVE_INTERVAL_MS = 420
NPC_MOVE_CHANCE = 0.65

# Render movement in tenths of a tile so motion feels smooth instead of snapping.
SUB_TILE_STEPS = 10
